transcriber/be/django_project/django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('transcriber/', include('transcriber.urls', namespace='transcriber')),
]

transcriber/be/django_project/transcriber/urls.py
"""Transcriber App URL Config"""
from django.urls import path

from . import views


app_name = 'transcriber'

urlpatterns = [
    # HttpResponse
    path('', views.recorder, name='recorder'),
    path('result/<str:query_id>', views.result, name='result'),
    path('results', views.result_list, name='result_list'),
    path('delete/<str:query_id>', views.delete_result, name='delete_result'),
    path('delete', views.delete_result_multi, name='delete_result_multi'),

    # JsonResponse
    path('api/transcribe', views.api_transcribe, name='api_transcribe'),
    path('api/basic_transcribe', views.api_basic_transcribe, name='api_basic_transcribe'),
    path('api/audio/<str:query_id>', views.api_audio, name='api_audio'),
    path('api/update/soap/', views.api_update_soap, name='api_update_soap'),
]

transcriber/be/django_project/transcriber/models.py
"""Transcriber App Models"""
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Transcription(models.Model):
    """Transcriber Model"""
    filename = models.TextField(primary_key=True, unique=True)
    transcript = models.TextField(null=True)
    edited_transcript = models.TextField(null=True)
    formatted_text = RichTextField(null=True)
    audio_created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.filename)

transcriber/be/django_project/transcriber/forms.py
"""Transcription App Forms"""
from django import forms
from django.core.validators import FileExtensionValidator
from ckeditor.widgets import CKEditorWidget


class BasicAudioFileUploadForm(forms.Form):
    """Basic image upload form, allowing only JPEG and PNG file extensions."""
    file = forms.FileField(
        validators=[FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'webm'])],
        widget=forms.FileInput(attrs={'accept': 'audio/mp3, audio/wav, audio/webm'}),
    )

class EditTranscriptForm(forms.Form):
    """Form to edit a Transcription object's transcript field."""
    filename = forms.CharField(
        widget=forms.TextInput(attrs={'readonly': True}),
    )
    transcript = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 40,}),
    )

class TextInputForm(forms.Form):
    """Basic text input form."""
    input = forms.CharField(widget=forms.Textarea(
        attrs={
            'rows': 5,
            'style': 'width: 100%; resize: none;',
        }
    ), max_length=500)

class RichTextInputForm(forms.Form):
    """Basic rich text editor form."""
    text = forms.CharField(widget=CKEditorWidget())

transcriber/be/django_project/transcriber/views.py
"""Transcriber App Views"""
import logging
import uuid
import datetime
import os
import base64

# Django
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.forms import model_to_dict
from django.utils import timezone
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

# Local
from .models import Transcription

from .forms import (
    BasicAudioFileUploadForm,
    EditTranscriptForm,
    TextInputForm,
    RichTextInputForm,
)
from .gpt_transcription import (
    get_transcription_from_local_file,
    get_soap_format_from_transcription,
    update_soap_format_with_intruction,
)

# Get logger
logger = logging.getLogger(__name__)

MEDIA_AUDIO_DIR = 'transcriber/media/audio/'

# Create your views here.

def recorder(request):
    """Recorder view containing audio recording, downloading, and transcribing features."""
    context = {
        'form': BasicAudioFileUploadForm(),
        'transcription': None,
        'edit_original_transcript_form': None,
        'edit_modified_transcript_form': None,
        # Empty form, only used for JS fetch POST request
        'empty_edit_form': EditTranscriptForm(),
        # Forms for editing reformatted text
        'edit_soap_form': RichTextInputForm(),
        'edit_chat_form': TextInputForm(),
    }

    if request.method == 'POST':
        # If file is uploaded (audio file)
        if request.FILES:
            # Load form data
            form = BasicAudioFileUploadForm(request.POST, request.FILES)

            # Check if form is valid
            if form.is_valid():
                logger.info('Handling audio file upload.')
                handle_audio_file_upload(request, form, context)

                # Redirect to result page if 'new_file' in request.POST
                # Current workaround to handle JS fetch POST request for 1-click transcription
                if 'new_file' in request.POST:
                    return redirect(
                        'transcriber:result', query_id=context['transcription'].filename
                    )
            else:
                return HttpResponse(status=404, content='Invalid file upload form')
        else:
            # If form for original transcript to generate new formatted text
            if 'reformat' in request.POST:
                # Load form data
                form = EditTranscriptForm(request.POST)

                # Check if form is valid
                if form.is_valid():
                    logger.info('Handling reformatting of original transcript.')
                    handle_reformat_original_transcript(form, context)
                else:
                    return HttpResponse(status=404, content='Invalid reformat form')
            # If form for edited transcript to generate new formatted text
            elif 'reformat_edited' in request.POST:
                # Load form data
                form = EditTranscriptForm(request.POST)

                # Check if form is valid
                if form.is_valid():
                    logger.info('Handling reformatting of edited transcript.')
                    handle_reformat_edited_transcript(form, context)
                else:
                    return HttpResponse(status=404, content='Invalid edit reformat form')

        # Prefill SOAP note edit form if applicable
        context['edit_soap_form'].initial = (
            {'text': context['transcription'].formatted_text} if context['transcription'] else {}
        )

    return render(request, 'transcriber/recorder.html', context)

def result(request, query_id):
    """Result view"""
    context = {
        'query_id': query_id,
        'edit_original_transcript_form': None,
        'edit_modified_transcript_form': None,
        # Forms for editing reformatted text
        'edit_soap_form': RichTextInputForm(),
        'edit_chat_form': TextInputForm(),
    }

    try:
        transcription = Transcription.objects.get(filename=query_id)

        # Add Transcription instance to context
        context['transcription'] = transcription

        # Load audio file into memory and add to context
        with open(f'{MEDIA_AUDIO_DIR}{transcription.filename}', 'rb') as audio_file:
            context['audio_file'] = audio_file.read()

    except Transcription.DoesNotExist:
        return HttpResponse(status=404, content='Transcription not found for this filename.')

    if request.method == 'POST':
        # If form for original transcript to generate new formatted text
        if 'reformat' in request.POST:
            # Load form data
            form = EditTranscriptForm(request.POST)

            # Check if form is valid
            if form.is_valid():
                logger.info('Handling reformatting of original transcript.')
                handle_reformat_original_transcript(form, context)
            else:
                return HttpResponse(status=404, content='Invalid reformat form')
        # If form for edited transcript to generate new formatted text
        elif 'reformat_edited' in request.POST:
            # Load form data
            form = EditTranscriptForm(request.POST)

            # Check if form is valid
            if form.is_valid():
                logger.info('Handling reformatting of edited transcript.')
                handle_reformat_edited_transcript(form, context)
            else:
                return HttpResponse(status=404, content='Invalid edit reformat form')

        # Set variable to updated transcription instance (otherwise it will provide previous values)
        # context['transcription'] points to updated instance, but transcription does not
        transcription = context['transcription']

    # Prefill transcript edit form
    if transcription.edited_transcript:
        context['edit_modified_transcript_form'] = EditTranscriptForm(
            initial={
                'filename': transcription.filename,
                'transcript': transcription.edited_transcript,
            }
        )
    else:
        context['edit_original_transcript_form'] = EditTranscriptForm(
            initial={
                'filename': transcription.filename,
                'transcript': transcription.transcript,
            }
        )

    # Prefill SOAP note edit form
    context['edit_soap_form'].initial = (
        {'text': transcription.formatted_text}
    )

    return render(request, 'transcriber/result.html', context)


def result_list(request):
    """Result list view"""

    transcriptions = Transcription.objects.all().order_by('-audio_created_at')
    context = {
        'total': transcriptions.count(),
        'page_obj': pagination(request, transcriptions, 30),
    }

    return render(request, 'transcriber/result_list.html', context)

def delete_result(request, query_id):
    """Delete transcription result."""
    try:
        transcription = Transcription.objects.get(filename=query_id)
        transcription.delete()
    except Transcription.DoesNotExist:
        return HttpResponse(status=404, content='Transcription not found for this filename.')

    return redirect('transcriber:result_list')

def delete_result_multi(request):
    """Delete multiple transcription results."""
    if request.method == 'POST':
        print(request.POST)
        # Get selected transcription IDs from request
        list_query_id = request.POST.getlist('id')

        list_except = []

        if not list_query_id:
            return HttpResponse(status=404, content='No transcriptions selected for deletion.')

        for query_id in list_query_id:
            try:
                transcription = Transcription.objects.get(filename=query_id)
                # Delete audio file from media directory if it exists
                if os.path.exists(f'{MEDIA_AUDIO_DIR}{transcription.filename}'):
                    os.remove(f'{MEDIA_AUDIO_DIR}{transcription.filename}')

                # Delete Transcription instance from database
                transcription.delete()
            except Transcription.DoesNotExist:
                list_except.append(query_id)
                logger.warning(
                    'Failed to find Transcription instance for the following filenames: %s',
                    list_except
                )
        # Redirect back to result list view
        return redirect('transcriber:result_list')
    return HttpResponse(status=404, content='Invalid request method.')


# JsonResponse API ---------------------------------------------------------------------------------

def api_transcribe(request):
    """Transcribe audio file using OpenAI API"""
    context = {}

    # Check if request is POST
    if request.method == 'POST' and request.FILES:
        # Load form data
        form = BasicAudioFileUploadForm(request.POST, request.FILES)

        # Check if form is valid
        if form.is_valid():
            logger.info('Handling audio file upload.')
            handle_audio_file_upload(request, form, context)

            trimmed_context = {
                'transcription': model_to_dict(context['transcription']),
            }

            # Redirect to result page if 'new_file' in request.POST
            # Current workaround to handle JS fetch POST request for 1-click transcription
            if 'new_file' in request.POST:
                return JsonResponse(status=200, data={'context': trimmed_context})
        else:
            return JsonResponse(status=404, data={'error': 'Invalid form data'})
    return JsonResponse(status=404, data={'error': 'Invalid request'})

def api_audio(request, query_id):
    """Get audio file"""
    context = {
        'audio_file':  None
    }

    try:
        # Get Transcription instance
        transcription = Transcription.objects.get(filename=query_id)

        # Check if audio file exists
        if os.path.exists(f'{MEDIA_AUDIO_DIR}{transcription.filename}'):

transcriber/be/django_project/transcriber/templates/transcriber/_navbar.html
<nav class="navbar navbar-default bg-dark border-bottom border-body sticky-top" data-bs-theme="dark">
    <div class="container-fluid">
        <header>
            <a class="navbar-brand" href="{% url 'transcriber:recorder' %}">{{ title }}</a>
        </header>
        <div class="me-auto mb-2 mb-lg-0" id="navbarSupportedContent">
            <a href="{% url 'transcriber:recorder' %}"><button type="button" class="btn btn-primary">Record and Transcribe</button></a>
            <a href="{% url 'transcriber:result_list' %}"><button type="button" class="btn btn-primary">Transcriptions</button></a>
        </div>
    </div>
</nav>

transcriber/be/django_project/transcriber/templates/transcriber/base.html
<!-- base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta charset="utf-8">
        <script src="{% static 'third_party/bootstrap-5.3.8-dist/js/bootstrap.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'third_party/bootstrap-5.3.8-dist/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'transcriber/main.css' %}">
        <link rel="stylesheet" href="{% static 'transcriber/modal.css' %}">
        <link rel="stylesheet" href="{% static 'transcriber/modal.css' %}">
        <script src="{% static 'transcriber/modal.js' %}"></script>
        {% block metadata %}
        <!-- Metadata: Additional scripts/styles/etc -->
        {% endblock %}
        <title>{% block title %}Transcriber{% endblock %}</title>
    </head>
    <body>
        {% include 'transcriber/_navbar.html' with title='Transcriber' %}
        <main>
            <div class="content" style="padding: 24px 24px;">
                {% block content %}
                <!-- Content -->
                {% endblock %}
            </div>
        </main>
        <hr>
        <footer>
            <!-- Footer -->
            <p class="text-center">{% block footer %}Transcriber Project ©{% endblock %}</p>
        </footer>
    </body>
</html>

transcriber/be/django_project/transcriber/templates/transcriber/pagination_base.html
{% extends 'transcriber/base.html' %}

{% block content %}
    {% block paginated_content %}
    {% endblock paginated_content %}
    {% if page_obj %}
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1"><button type="button" class="btn btn-outline-secondary">First</button></a>
                    <a href="?page={{ page_obj.previous_page_number }}"><button type="button" class="btn btn-outline-secondary">&lt;</button></a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}"><button type="button" class="btn btn-outline-secondary">&gt;</button></a>
                    <a href="?page={{ page_obj.paginator.num_pages }}"><button type="button" class="btn btn-outline-secondary">Last</button></a>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% endblock content %}

transcriber/be/django_project/transcriber/templates/transcriber/result_list.html
{% extends 'transcriber/pagination_base.html' %}
{% load static %}

{% block metadata %}
    <script src="{% static 'transcriber/time_convert.js' %}"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            // Button to initiate deletion
            const initiateDeleteBtn = document.getElementById('initiateDeleteBtn');

            // Modal messages (selected vs none selected)
            const selected_message = document.getElementById('selected-message');
            const none_selected_message = document.getElementById('none-selected-message');

            initiateDeleteBtn.addEventListener('click', function() {
                form = document.getElementById('delete_results');

                // Check if any transcriptions are selected
                let listChecked = form.querySelectorAll('input[name="id"]:checked');
                if (listChecked.length > 0) {
                    selected_message.style.display = 'grid';
                    none_selected_message.style.display = 'none';
                } else {
                    selected_message.style.display = 'none';
                    none_selected_message.style.display = 'grid';
                }

                // Show modal
                staticModal();
            });
        });

        function confirmDelete(button) {
            // Hide first button
            button.style.display = 'none';

            // Show actual delete button with form submit
            cell = button.parentElement;
            deleteForm = cell.querySelector('form');
            deleteForm.style.display = 'block';
        }
    </script>
{% endblock %}

{% block title %}List of Transcriptions{% endblock %}

{% block paginated_content %}
    {% comment %} Modal {% endcomment %}
    <div id="modal" style="display: none;">
        <div class="modal-container">
            <div id="selected-message" class="modal-content" style="display: none;">
                <p><b>Confirm Deletion</b></p>
                <p>Deleting the transcription will delete the file stored in the media directory. Please make a copy elsewhere if you still need it.</p>
                <br>
                <button form="delete_results" type="submit">Confirm</button>
            </div>
            <div id="none-selected-message" class="modal-content">
                <p><b>Warning</b></p>
                <p>No transcriptions were selected for deletion.</p>
            </div>
        </div>
    </div>

    {% comment %} Table {% endcomment %}
    <div style="justify-items: center;">
        <p><b>Number of transcriptions:</b> {{ total }}</p>
        <form id="delete_results" action="{% url 'transcriber:delete_result_multi' %}" method="post">
            {% csrf_token %}
            <table class="table">
                <thead>
                    <tr>
                        <th>Filename</th>
                        <th>Created/Added</th>
                        <th>
                            <button id="initiateDeleteBtn" type="button" class="btn btn-outline-danger">Delete</button>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in page_obj %}
                        <tr>
                            <td>
                                <a href="{% url 'transcriber:result' query_id=item.filename %}">
                                    {{ item }}
                                </a>
                            </td>
                            <td class="timestamp">
                                {{ item.audio_created_at|date:'Y/m/d h:i:s A e' }}
                            </td>
                            <td style="text-align: center;">
                                <input type="checkbox" name="id" value="{{ item.filename }}">
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </form>
    <div>
{% endblock %}